apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multitrack-player-app-nonprod
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.1
    helm:
      values: |-
        image:
          repository: harbor.guiadodevops.com/core/multitrack-player-app
          tag: "master-0a048e7"
        imagePullSecrets:
          - name: k8s-private-repository-harbor
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: multitrack-player-app-nonprod.guiadodevops.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: multitrack-player-app-nonprod-tls
            hosts:
              - multitrack-player-app-nonprod.guiadodevops.com
    chart: core/myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated: {}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true