apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd     
spec:
  project: tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 12.1.1
    helm:
      values: |-
        ingress:
          enabled: true
          className: "nginx"
          pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: git.guiadodevops.com
              paths:
                - path: /
          tls:
            - secretName: gitea-tls
              hosts:
                - git.guiadodevops.com      
    chart: infra/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
