apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd     
spec:
  project: tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 1.24.0
    helm:
      values: |
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
            external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: ollama.guiadodevops.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: ollama-tls-secret
              hosts:
                - ollama.guiadodevops.com
        ollama:
          models:
            pull:
              - llama2
              - mistral
              - deepseek-r1:1.5b
            run:
              - llama2
              - mistral
              - deepseek-r1:1.5b
        resources:
          requests:
            memory: 8Gi
            cpu: 2000m
          limits:
            memory: 32Gi
            cpu: 16000m
        nodeSelector:
          name: ollama
    chart: infra/ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
