apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd     
spec:
  project: core-tools-config
  source:
    repoURL: https://github.com/ndawpa/guiadodevops
    path: kubernetes/argocd/config/core-tools/grafana-config
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
