apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.1
    helm:
      values: |-
        image:
          repository: harbor.guiadodevops.com/core/myapp
          tag: "23_main"
        imagePullSecrets:
          - name: k8s-private-repository-harbor
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
            - host: myapp-prod.guiadodevops.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: myapp-prod-tls
            hosts:
              - myapp-prod.guiadodevops.com
    chart: core/myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
