apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 11.6.27
    helm:
      values: |-
        replicaCount: 3
        publishService:
          enabled: true
    chart: infra/nginx-ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
